version: '3.8'

services:
  mockery-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockery-mcp-server
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
    volumes:
      # Mount project source code (read-only)
      - ./examples:/workspace/examples:ro
      # Mount output directory for generated mocks
      - ./output:/workspace/output
    networks:
      - mockery-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    container_name: mockery-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mockery-network
    restart: unless-stopped
    profiles:
      - caching

networks:
  mockery-network:
    driver: bridge

volumes:
  redis_data:
    driver: local